<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        // Ensure users are created first
        $this->call(UserSeeder::class);
        
        // Get users by nama for PIC mapping
        $userIdMap = \App\Models\User::pluck('id', 'nama')->toArray();

        $suppliers = [
            [
                'nama' => 'pak Giarto',
                'slug' => 'pak-giarto',
                'alamat' => 'Kendal, Boja Jateng',
                'no_hp' => '085226444730',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pak Rul',
                'slug' => 'pak-rul',
                'alamat' => 'Jombang, Jatim',
                'no_hp' => '085711268996',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Solikin',
                'slug' => 'pak-solikin',
                'alamat' => 'Beiji, Pasuruan, Jatim',
                'no_hp' => '082142026102',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'abah ariff',
                'slug' => 'abah-ariff',
                'alamat' => 'Beiji, Pasuruan, Jatim',
                'no_hp' => '081249349002',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Hasan',
                'slug' => 'pak-hasan',
                'alamat' => 'Gresik, Jatim',
                'no_hp' => '085706645622',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Widodo',
                'slug' => 'pak-widodo',
                'alamat' => 'Blitar, Jatim',
                'no_hp' => '085732335784',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Heri',
                'slug' => 'pak-heri',
                'alamat' => 'Majalengka, Jabar',
                'no_hp' => '083841358027',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Wawan',
                'slug' => 'pak-wawan',
                'alamat' => 'Gempol, Pasuruan, Jatim',
                'no_hp' => '082237838252',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Kusnadi',
                'slug' => 'pak-kusnadi',
                'alamat' => 'Plipir, Sidoarjo, Jatim',
                'no_hp' => '081553724604',
                'pic_nama' => 'Mahenda Abdillah Kamil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Adit',
                'slug' => 'pak-adit-nganjuk',
                'alamat' => 'Nganjuk, Jatim',
                'no_hp' => '081332609292',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Toni',
                'slug' => 'pak-toni',
                'alamat' => 'Purwakarta, Jateng',
                'no_hp' => '081382537211',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'bu Hadiah',
                'slug' => 'bu-hadiah',
                'alamat' => 'Gempol, Pasuruan, Jatim',
                'no_hp' => '08113315554',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Fitra',
                'slug' => 'pak-fitra',
                'alamat' => '-',
                'no_hp' => '085233604175',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Yuda (PT. Sorini)',
                'slug' => 'pak-yuda-pt-sorini',
                'alamat' => 'Pandaan, Jatim',
                'no_hp' => '08123319145',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Wandi',
                'slug' => 'pak-wandi',
                'alamat' => 'Pandaan, Jatim',
                'no_hp' => '082257421613',
                'pic_nama' => 'Mahenda Abdillah Kamil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'bu Lestari',
                'slug' => 'bu-lestari',
                'alamat' => 'Tandes, Surabaya',
                'no_hp' => '085210208030',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Yohannes',
                'slug' => 'pak-yohannes',
                'alamat' => 'Makassar',
                'no_hp' => '08113028855',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ibu Silvia PT Garuda Perkasa Jaya',
                'slug' => 'ibu-silvia-pt-garuda-perkasa-jaya',
                'alamat' => 'Jakarta',
                'no_hp' => '085270092333',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Rudi',
                'slug' => 'pak-rudi',
                'alamat' => 'Gresik Jatim',
                'no_hp' => '081217999362',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Daniel PT Miwon',
                'slug' => 'pak-daniel-pt-miwon',
                'alamat' => 'Gresik Jatim',
                'no_hp' => '081228942893',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Lutfi',
                'slug' => 'pak-lutfi',
                'alamat' => 'Tulungagung, Jatim',
                'no_hp' => '082233909377',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'abah Zainal',
                'slug' => 'abah-zainal',
                'alamat' => 'Jombang, Jatim',
                'no_hp' => '082229299292',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ibu Anis',
                'slug' => 'ibu-anis',
                'alamat' => 'Beiji, Pasuruan Jatim',
                'no_hp' => '081397781125',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'bu Ulil CV Sumber Pangan',
                'slug' => 'bu-ulil-cv-sumber-pangan',
                'alamat' => 'Kediri',
                'no_hp' => '08113046186',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pak Haris',
                'slug' => 'pak-haris',
                'alamat' => 'Gresik Jatim',
                'no_hp' => '081248887363',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Ade',
                'slug' => 'pak-ade',
                'alamat' => '-',
                'no_hp' => '081329626839',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Iwan',
                'slug' => 'pak-iwan-krian',
                'alamat' => 'Krian, Sidoarjo',
                'no_hp' => '081233044105',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Akbar',
                'slug' => 'pak-akbar',
                'alamat' => 'Manyar, Gresik, Jatim',
                'no_hp' => '08113349499',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Benny',
                'slug' => 'pak-benny',
                'alamat' => 'Jabar',
                'no_hp' => '081292333886',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Korun PT Bungasari',
                'slug' => 'pak-korun-pt-bungasari',
                'alamat' => 'Cilegon',
                'no_hp' => '081318778878',
                'pic_nama' => 'Muhammad Romadhoni',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'abah Julio',
                'slug' => 'abah-julio',
                'alamat' => 'Mojokerto',
                'no_hp' => '',
                'pic_nama' => 'Mahenda Abdillah Kamil',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak San',
                'slug' => 'pak-san',
                'alamat' => 'Lamongan, Jatim',
                'no_hp' => '',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Iman',
                'slug' => 'pak-iman',
                'alamat' => 'Kediri, Jatim',
                'no_hp' => '082245229760',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Wahyu',
                'slug' => 'pak-wahyu',
                'alamat' => 'Sedati, Sidoarjo',
                'no_hp' => '089526587124',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Bambang',
                'slug' => 'pak-bambang',
                'alamat' => 'Jabon, Sidoarjo',
                'no_hp' => '085736003123',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Nafar',
                'slug' => 'pak-nafar',
                'alamat' => 'Gedangan, Sidoarjo',
                'no_hp' => '082245058583',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Ali',
                'slug' => 'pak-ali',
                'alamat' => 'Kediri, Jatim',
                'no_hp' => '082333283862',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Abi',
                'slug' => 'pak-abi',
                'alamat' => 'Pati, Jateng',
                'no_hp' => '081314601742',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Adit (Prambong)',
                'slug' => 'pak-adit-prambong',
                'alamat' => 'Prambong, Sidoarjo',
                'no_hp' => '087855851727',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Wahyudi',
                'slug' => 'pak-wahyudi',
                'alamat' => 'Lamongan, Jatim',
                'no_hp' => '089514480750',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ibu Hilma',
                'slug' => 'ibu-hilma',
                'alamat' => 'Blitar, Jatim',
                'no_hp' => '081559556406',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'abah Mashuri',
                'slug' => 'abah-mashuri',
                'alamat' => 'Sukodono, Sidoarjo',
                'no_hp' => '081237904247',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Yamin',
                'slug' => 'pak-yamin',
                'alamat' => 'Mojokerto',
                'no_hp' => '085794504294',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Alim',
                'slug' => 'pak-alim',
                'alamat' => 'Jember, Jatim',
                'no_hp' => '081336574277',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Aldy',
                'slug' => 'pak-aldy',
                'alamat' => 'Bogor, Jabar',
                'no_hp' => '085217058181',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Ridho',
                'slug' => 'pak-ridho',
                'alamat' => 'Tulungagung',
                'no_hp' => '082230574211',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Budi',
                'slug' => 'pak-budi',
                'alamat' => 'Cepu, Jateng',
                'no_hp' => '082232066659',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Heru',
                'slug' => 'pak-heru',
                'alamat' => 'Ngoro, Jawa Timur',
                'no_hp' => '085600363802',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Adi',
                'slug' => 'pak-adi-karawang',
                'alamat' => 'Karawang, Jabar',
                'no_hp' => '082228060466',
                'pic_nama' => 'M. Angga Fajar S,P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Pri',
                'slug' => 'pak-pri',
                'alamat' => 'Demak, Jateng',
                'no_hp' => '085817537370',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Darsono',
                'slug' => 'pak-darsono',
                'alamat' => 'Demak, Jateng',
                'no_hp' => '082345952676',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ibu Taslima',
                'slug' => 'ibu-taslima',
                'alamat' => 'Demak, Jateng',
                'no_hp' => '08122911074',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Tris',
                'slug' => 'pak-tris',
                'alamat' => 'Demak, Jateng',
                'no_hp' => '081325624746',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'ibu Romtini',
                'slug' => 'ibu-romtini',
                'alamat' => 'Demak, Jateng',
                'no_hp' => '085743385246',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Fani',
                'slug' => 'pak-fani',
                'alamat' => 'Rembang, Jateng',
                'no_hp' => '085641639966',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Teguh',
                'slug' => 'teguh',
                'alamat' => 'Jateng',
                'no_hp' => '081391433689',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Febri',
                'slug' => 'febri',
                'alamat' => 'Jateng',
                'no_hp' => '081298090460',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rini',
                'slug' => 'rini',
                'alamat' => 'Jabar',
                'no_hp' => '082288287103',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yayuk',
                'slug' => 'yayuk',
                'alamat' => 'Jateng',
                'no_hp' => '081325411827',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'pak Dani',
                'slug' => 'pak-dani',
                'alamat' => 'Kendal, Jateng',
                'no_hp' => '081326844147',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rokidin',
                'slug' => 'rokidin',
                'alamat' => 'Ngaliyan, Jateng',
                'no_hp' => '0812138395846',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Iwan',
                'slug' => 'iwan-jombang',
                'alamat' => 'Jombang',
                'no_hp' => '08126623433',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hardian',
                'slug' => 'hardian',
                'alamat' => 'Krian, Sidoarjo',
                'no_hp' => '082234097874',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Eddy',
                'slug' => 'eddy',
                'alamat' => 'Sepanjang, Sidoarjo',
                'no_hp' => '085784554489',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sutris',
                'slug' => 'sutris',
                'alamat' => 'Sidoarjo, Sidoarjo',
                'no_hp' => '081212169449',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Aris',
                'slug' => 'aris',
                'alamat' => 'Mojokerto, Sidoarjo',
                'no_hp' => '085755012340',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yudi',
                'slug' => 'yudi',
                'alamat' => 'Krian, Sidoarjo',
                'no_hp' => '081335595017',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ladi',
                'slug' => 'ladi',
                'alamat' => 'Gresik, Sidoarjo',
                'no_hp' => '081217834090',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yunus',
                'slug' => 'yunus',
                'alamat' => 'Pandaan, Pandaan',
                'no_hp' => '081232193672',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Siswanto',
                'slug' => 'siswanto',
                'alamat' => 'Lamongan, Jatim',
                'no_hp' => '082139191262',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Heri',
                'slug' => 'heri-gresik',
                'alamat' => 'Gresik, Sidoarjo',
                'no_hp' => '08226431447',
                'pic_nama' => 'Muhammad Zunaidi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Create suppliers with proper PIC assignment
        foreach ($suppliers as $supplier) {
            // Get PIC ID from nama mapping
            $picId = isset($userIdMap[$supplier['pic_nama']]) ? $userIdMap[$supplier['pic_nama']] : null;
            
            // Remove pic_nama from array and set pic_purchasing_id
            unset($supplier['pic_nama']);
            $supplier['pic_purchasing_id'] = $picId;
            
            Supplier::updateOrCreate(
                ['slug' => $supplier['slug']], // Check by slug (unique identifier)
                $supplier // Update or create with this data
            );
        }
    }
}
